# Generated by Django 6.0.6 on 2026-06-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.RenameField(
            model_name='ajuste',
            old_name='nombre_app',
            new_name='nombre_aplicacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='ajuste',
            name='mantenimiento',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='estado_sitio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abel.rol'),
            preserve_default=False,
        ),
    ]
