# Generated by Django 6.0.6 on 2026-06-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abel', '0002_rol_delete_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='logs_mantenimiento',
            field=models.TextField(blank=True, default=''),
        ),
    ]
